#!/usr/bin/env python
#=========================================================================
# regincr-sim <input-values>
#=========================================================================

from pymtl3            import *
from pymtl3.passes     import TracingConfigs
from sys               import argv
from RegIncrNstageRTL  import RegIncrNstageRTL

# Get list of input values from command line

input_values = [ int(x,0) for x in argv[1:] ]

# Add three zero values to end of list of input values

input_values.extend( [0, 0, 0] )

# Create a simulator using simulation tool

model = RegIncrNstageRTL( nstages=4 )
model.config_tracing = TracingConfigs(
  tracing='vcd',
  vcd_file_name="regincr-sim.vcd"
)

# ''' SECTION TASK '''''''''''''''''''''''''''''''''''''''''''''''''''''''
# To translate the model to Verilog you need to add a line here like
# this:
#
#  model.apply( SimulationPass() )
#
# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

model.apply( SimulationPass() )

# Reset simulator

mode.sim_reset()

# Apply input values and display output values

for input_value in input_values:

  # Write input value to input port

  model.in_ = b8(input_value)

  # Display line trace

  print( model.line_trace() )

  # Tick simulator one cycle

  model.tick()

