#!/usr/bin/env python
#=========================================================================
# regincr-sim <input-values>
#=========================================================================

from pymtl            import *
from sys              import argv
from RegIncrNstageRTL import RegIncrNstageRTL

# Get list of input values from command line

input_values = [ int(x,0) for x in argv[1:] ]

# Add three zero values to end of list of input values

input_values.extend( [0]*6 )

# Create a simulator using simulation tool

model = RegIncrNstageRTL( nstages=4 )
model.vcd_file = "regincr-4stage-sim.vcd"

# ''' SECTION TASK '''''''''''''''''''''''''''''''''''''''''''''''''''''''
# To translate the model to Verilog you need to add a line here like
# this:
#
#  model = TranslationTool( model )
#
# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

model = TranslationTool( model )

model.elaborate()
sim = SimulationTool( model )

# Reset simulator

sim.reset()

# Apply input values and display output values

for input_value in input_values:

  # Write input value to input port

  model.in_.value = input_value

  # Display line trace

  sim.print_line_trace()

  # Tick simulator one cycle

  sim.cycle()

