#==================================================================
# GitHub Pages Configuration
#==================================================================

title: "ECE 5745 Section 1: ASIC Flow Front-End"

